# Generated by Django 3.2.5 on 2021-08-13 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id_info', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('year', models.IntegerField(default=2021)),
                ('color', models.CharField(max_length=200)),
                ('transmission', models.CharField(max_length=20)),
                ('cylinder', models.IntegerField(default=4)),
                ('fuel', models.CharField(max_length=20)),
                ('engine_size', models.IntegerField(default=1600)),
                ('status', models.BooleanField(default=False)),
                ('documents', models.CharField(max_length=200)),
                ('insurance', models.CharField(max_length=200)),
                ('km', models.IntegerField(default=0)),
                ('approved', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
                ('payment_type', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id_cars', models.AutoField(primary_key=True, serialize=False)),
                ('carModel', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_post', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('id_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carsStore.carinfo')),
            ],
        ),
        migrations.CreateModel(
            name='MyAppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.BooleanField(default=True)),
                ('role', models.TextField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=135)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id_images', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.TextField()),
                ('id_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carsStore.carinfo')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id_feedback', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=500)),
                ('sender_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('id_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='carinfo',
            name='id_cars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carsStore.cars'),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='id_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
