# Generated by Django 3.2.6 on 2021-08-17 19:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carsStore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinfo',
            name='image1',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carinfo',
            name='image2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carinfo',
            name='image3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carinfo',
            name='image4',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
