# Generated by Django 3.2.5 on 2021-08-13 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carsStore', '0002_alter_carinfo_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='id_cars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='carsStore.cars'),
        ),
    ]
