# Generated by Django 3.2.5 on 2021-08-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsStore', '0003_alter_carinfo_id_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carinfo',
            name='id_cars',
        ),
        migrations.AddField(
            model_name='carinfo',
            name='carModel',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='phone',
            field=models.CharField(max_length=135, null=True),
        ),
        migrations.AddField(
            model_name='carinfo',
            name='user_name',
            field=models.CharField(max_length=135, null=True),
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
    ]
