# Generated by Django 3.2.5 on 2021-08-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsStore', '0004_auto_20210813_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='approved',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='cylinder',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='engine_size',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='km',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='price',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='status',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='year',
            field=models.CharField(max_length=200),
        ),
    ]
