# Generated by Django 3.2.6 on 2021-08-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsStore', '0005_auto_20210813_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinfo',
            name='primary_image',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
