# Generated by Django 3.2.6 on 2021-08-16 16:19

import carsStore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsStore', '0005_auto_20210813_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=carsStore.models.upload_to, verbose_name='Image'),
        ),
    ]
