# Generated by Django 3.2.6 on 2021-08-11 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_info', models.IntegerField()),
                ('brand', models.CharField(max_length=200)),
                ('year', models.IntegerField(default=2021)),
                ('color', models.CharField(max_length=200)),
                ('transmission', models.CharField(max_length=20)),
                ('cylinder', models.IntegerField(default=4)),
                ('fuel', models.CharField(max_length=20)),
                ('engine_size', models.IntegerField(default=1600)),
                ('status', models.BooleanField(default=False)),
                ('documents', models.CharField(max_length=200)),
                ('insurance', models.CharField(max_length=200)),
                ('km', models.IntegerField()),
                ('approved', models.BooleanField()),
                ('price', models.IntegerField()),
                ('payment_type', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cars', models.IntegerField()),
                ('carModel', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_id', models.IntegerField()),
                ('text', models.TextField(max_length=500)),
                ('sender_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_id', models.IntegerField()),
                ('image', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('text', models.TextField(max_length=500)),
                ('id_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.carinfo')),
            ],
        ),
    ]
