# Generated by Django 3.2.6 on 2021-08-11 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_carinfo_show'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserAccount',
        ),
    ]
