# Generated by Django 3.2.6 on 2021-08-11 22:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_rename_user_useraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='price',
            field=models.PositiveIntegerField(error_messages={'name': {'min_price': 'the price must be more than 1000 JD'}}, help_text='min price is 1000 JD', validators=[django.core.validators.MinValueValidator(1000)], verbose_name='price'),
        ),
    ]
